src/Entity/Reservation.php
<?php

namespace App\Entity;


use Doctrine\ORM\Mapping as ORM;
use App\Entity\Client;
/**
 * @ORM\Entity(repositoryClass=App\Repository\ReservationRepository::class)
 */
class Reservation
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_r;

    /**
     * @ORM\Column(type="string", length=254)
     */
    private $etat;

    /**
     * @ORM\ManyToOne(targetEntity=Client::class, inversedBy="reservations")
     */
    private $id_cli;

    /**
     * @ORM\ManyToOne(targetEntity=Service::class, inversedBy="reservations")
     */
    private $id_service;


   

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateR(): ?\DateTimeInterface
    {
        return $this->date_r;
    }

    public function setDateR(\DateTimeInterface $date_r): self
    {
        $this->date_r = $date_r;

        return $this;
    }

    public function getEtat(): ?string
    {
        return $this->etat;
    }

    public function setEtat(string $etat): self
    {
        $this->etat = $etat;

        return $this;
    }

    public function getIdCli(): ?client
    {
        return $this->id_cli;
    }

    public function setIdCli(?client $id_cli): self
    {
        $this->id_cli = $id_cli;

        return $this;
    }

    public function getIdService(): ?service
    {
        return $this->id_service;
    }

    public function setIdService(?service $id_service): self
    {
        $this->id_service = $id_service;

        return $this;
    }
 
   
   
 
    
}

src/Form/ReservationType.php
<?php

namespace App\Form;
use App\Entity\Client;
use App\Entity\Service;
use App\Entity\Reservation;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ReservationType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('date_r')
            ->add('etat',ChoiceType::class,['choices'=>['en Cours'=>'en Cours','Valide'=>'Valide','Termine'=>'Termine','Annule'=>'Annule','Expire'=>'Expire']] ) 
            ->add('id_cli',EntityType::class,['class' => Client::class,
                 'choice_label' => 'nom',
                'label' => 'Client'])
            ->add('id_service',EntityType::class,['class' => Service::class,
                'choice_label' => 'libelle',
               'label' => 'Service'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Reservation::class,
        ]);
    }
}

src/Controller/ReservationController.php
<?php

namespace App\Controller;

use App\Entity\Reservation;
use App\Entity\EtatSearch;
use App\Entity\Client;
use App\Form\EtatSearchType;
use App\Form\ReservationType;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
/**
 * @Route("/reservation")
 */
class ReservationController extends AbstractController
{
    /**
     *  @IsGranted("ROLE_ADMIN")
     * @Route("/", name="reservation_index")
     */
    public function index(Request $request)
    {
        
        $etatSearch = new EtatSearch();
        $form = $this->createForm(EtatSearchType::class,$etatSearch);
        $form->handleRequest($request);
        $reservations= $this->getDoctrine()->getRepository(Reservation::class)->findAll();
       
        if($form->isSubmitted() && $form->isValid()) {
            $etat = $etatSearch->getEtat();
            if ($etat!="")
          
            $reservations= $this->getDoctrine()->getRepository(Reservation::class)->findBy(['etat' => $etat] );
            else
            $reservations= $this->getDoctrine()->getRepository(Reservation::class)->findAll();
            }
            return $this->render('reservation/index.html.twig',[ 'form' =>$form->createView(), 'reservations' => $reservations]);        
    }
  
    

    /**
     *  @IsGranted("ROLE_ADMIN")
     * @Route("/new", name="reservation_new", methods={"GET","POST"})
     */
    public function new(Request $request): Response
    {
        $reservation = new Reservation();
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($reservation);
            $entityManager->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/new.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     *  @IsGranted("ROLE_ADMIN")
     * @Route("/{id}", name="reservation_show", methods={"GET"})
     */
    public function show(Reservation $reservation): Response
    {
        return $this->render('reservation/show.html.twig', [
            'reservation' => $reservation,
        ]);
    }

    /**
     *  @IsGranted("ROLE_ADMIN")
     * @Route("/{id}/edit", name="reservation_edit", methods={"GET","POST"})
     */
    public function edit(Request $request, Reservation $reservation): Response
    {
        $form = $this->createForm(ReservationType::class, $reservation);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('reservation_index');
        }

        return $this->render('reservation/edit.html.twig', [
            'reservation' => $reservation,
            'form' => $form->createView(),
        ]);
    }

    /**
     *  @IsGranted("ROLE_ADMIN")
     * @Route("/{id}", name="reservation_delete", methods={"DELETE"})
     */
    public function delete(Request $request, Reservation $reservation): Response
    {
        if ($this->isCsrfTokenValid('delete'.$reservation->getId(), $request->request->get('_token'))) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->remove($reservation);
            $entityManager->flush();
        }

        return $this->redirectToRoute('reservation_index');
    }
}

templates/reservation/_delete_form.html.twig
<form method="post" action="{{ path('reservation_delete', {'id': reservation.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ reservation.id) }}">
    <button class="btn btn-danger" >Delete</button>
</form>

templates/reservation/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button  class="btn btn-success">{{ button_label|default('Save') }}</button>
     <a href="{{ path('reservation_index') }}"style="margin-left:10px"><i class='fas fa-undo'></i></a>
{{ form_end(form) }}

templates/reservation/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Reservation{% endblock %}

{% block body %}
    <h1>Edit Reservation</h1>
    {{ include('reservation/_form.html.twig', {'button_label': 'Update'}) }}
    {{ include('reservation/_delete_form.html.twig') }}
    
   
{% endblock %}

templates/reservation/index.html.twig
{% extends 'base.html.twig' %}
{% block title%} Liste des Reservations{% endblock %}
{% block body %}
{{ form_start(form) }}

<div class="form-row align-items-end" >
 <div class="col">
   {{ form_row (form.etat) }}
 </div>

  <div class="col">
   <div class="form-group">
      <button type="submit" class="btn btn-success">Rechercher</button>
    </div>
 </div>
</div>
 {{ form_end(form) }}
{% if reservations %}
    <table id="reservations" class="table table-striped">
    
        <thead>
            <tr>
                <th>Id</th>
                <th>Date Reservation</th>
                <th>Etat</th>
                <th>Client</th>
                <th>Service</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for reservation in reservations %}
            <tr>
                <td>{{ reservation.id }}</td>
                <td>{{ reservation.dateR ? reservation.dateR|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ reservation.etat }}</td>
                <td>{{ reservation.idCli.nom }}</td>
                <td>{{ reservation.idService.libelle }}</td>
                <td>
                    <a href="{{ path('reservation_show', {'id': reservation.id}) }}"><i class="fa fa-plus-square"></i></a>
                    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}"><i class='fas fa-edit'> </i></a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
  {% else %}
    <p>Aucun Reservation</p>
  {% endif %} 
    <a href="{{ path('reservation_new') }}"><i class='fas fa-pen-alt'></i> Create new</a>
{% endblock %}

templates/reservation/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Reservation{% endblock %}

{% block body %}
    <h1>Create new Reservation</h1>

    {{ include('reservation/_form.html.twig') }}

   
{% endblock %}

templates/reservation/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Reservation{% endblock %}

{% block body %}
    <h1>Reservation</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ reservation.id }}</td>
            </tr>
            <tr>
                <th>Date_r</th>
                <td>{{ reservation.dateR ? reservation.dateR|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Etat</th>
                <td>{{ reservation.etat }}</td>
            </tr>
            <tr>
            <th>Client</th>
            <td>{{reservation.idCli.nom}}</td>
            </tr>
            <tr>
            <th>Mail Client</th>
            <td>{{reservation.idCli.mail}}</td>
            </tr>
             <tr>
            <th>Service</th>
            <td>{{reservation.idService.libelle}}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('reservation_index') }}"><i class='fas fa-undo'></i></a>

    <a href="{{ path('reservation_edit', {'id': reservation.id}) }}"><i class='fas fa-edit'> </i></a>

    {{ include('reservation/_delete_form.html.twig') }}
{% endblock %}